name = "stemgharbiya"
compatibility_date = "2026-02-04"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "stemgharbiya-applications"
database_id = "724cedac-bd4f-45ce-aa5f-2b925d6c87a2"

[vars]
RESEND_SENDER_EMAIL = "github@stem.a8k.dev"
TEAM_NOTIFICATION_EMAIL = "team@stem.a8k.dev"